using VictoryFC.Models;

namespace VictoryFC.Data
{
    public static class DatabaseSeeder
    {
        public static void SeedDatabase(ApplicationDbContext context)
        {
            if (context.Matches.Any() || context.Scorers.Any()) return;

            var matches = GetInitialMatchesData();
            var scorers = GetInitialScorersData();

            context.Matches.AddRange(matches);
            context.Scorers.AddRange(scorers);
            context.SaveChanges();
        }

        private static List<Match> GetInitialMatchesData()
        {
            var matches = new List<Match>
            {
                // Regular Season Matches (existing data)
                new() { Date = new DateTime(2025, 5, 25, 11, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 2, AwayTeam = "Azzurri ST", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 5, 25, 9, 0, 0), Field = "Proto Field", HomeTeam = "Proto 3", HomeScore = 2, AwayTeam = "Proto 4", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 5, 25, 11, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 4, AwayTeam = "Sons of Italy Inter", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 5, 25, 11, 0, 0), Field = "Heritage Green 5", HomeTeam = "West Hamilton United 89", HomeScore = 0, AwayTeam = "Victory FC", AwayScore = 7, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 1, 11, 0, 0), Field = "Heritage Green 5", HomeTeam = "Proto 4", HomeScore = 0, AwayTeam = "Victory FC", AwayScore = 6, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 1, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "Azzurri ST", HomeScore = 1, AwayTeam = "Hamilton Serbian United", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 1, 9, 0, 0), Field = "Mohawk 5", HomeTeam = "West Hamilton United 89", HomeScore = 3, AwayTeam = "United FC", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 1, 9, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 0, AwayTeam = "Proto 3", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 8, 11, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 2, AwayTeam = "West Hamilton United 89", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 8, 11, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 6, AwayTeam = "Azzurri ST", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 8, 11, 0, 0), Field = "Mohawk 2", HomeTeam = "Victory FC", HomeScore = 5, AwayTeam = "Proto 3", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 8, 9, 0, 0), Field = "Mohawk 5", HomeTeam = "United FC", HomeScore = 2, AwayTeam = "Proto 4", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 15, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "West Hamilton United 89", HomeScore = 3, AwayTeam = "Sons of Italy Inter", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 15, 11, 0, 0), Field = "Proto Field", HomeTeam = "Proto 3", HomeScore = 7, AwayTeam = "Azzurri ST", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 15, 9, 0, 0), Field = "Proto Field", HomeTeam = "Proto 4", HomeScore = 2, AwayTeam = "Hamilton Serbian United", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 15, 11, 0, 0), Field = "Mohawk 5", HomeTeam = "Victory FC", HomeScore = 3, AwayTeam = "United FC", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 22, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "Azzurri ST", HomeScore = 0, AwayTeam = "West Hamilton United 89", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 22, 9, 0, 0), Field = "Mohawk 3", HomeTeam = "Sons of Italy Inter", HomeScore = 4, AwayTeam = "Proto 4", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 22, 11, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 4, AwayTeam = "Proto 3", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 6, 22, 9, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 0, AwayTeam = "Victory FC", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 6, 9, 0, 0), Field = "Proto Field", HomeTeam = "Proto 3", HomeScore = 2, AwayTeam = "West Hamilton United 89", AwayScore = 4, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 6, 9, 0, 0), Field = "Ancaster 3-A", HomeTeam = "Victory FC", HomeScore = 5, AwayTeam = "Sons of Italy Inter", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 6, 11, 0, 0), Field = "Proto Field", HomeTeam = "Proto 4", HomeScore = 0, AwayTeam = "Azzurri ST", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 6, 9, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 3, AwayTeam = "United FC", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 13, 11, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 2, AwayTeam = "Proto 3", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 13, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "West Hamilton United 89", HomeScore = 2, AwayTeam = "Proto 4", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 13, 11, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 1, AwayTeam = "United FC", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 13, 11, 0, 0), Field = "Mohawk 6", HomeTeam = "Azzurri ST", HomeScore = 0, AwayTeam = "Victory FC", AwayScore = 6, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 20, 11, 0, 0), Field = "Proto Field", HomeTeam = "Proto 4", HomeScore = 2, AwayTeam = "Proto 3", AwayScore = 6, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 20, 9, 0, 0), Field = "Ancaster 3-A", HomeTeam = "Victory FC", HomeScore = 5, AwayTeam = "West Hamilton United 89", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 20, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "Azzurri ST", HomeScore = 0, AwayTeam = "United FC", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 20, 9, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 0, AwayTeam = "Hamilton Serbian United", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 27, 9, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 1, AwayTeam = "Azzurri ST", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 27, 11, 0, 0), Field = "Heritage Green 5", HomeTeam = "United FC", HomeScore = 1, AwayTeam = "West Hamilton United 89", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 27, 9, 0, 0), Field = "Heritage Green 3", HomeTeam = "Proto 3", HomeScore = 6, AwayTeam = "Sons of Italy Inter", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 7, 27, 11, 0, 0), Field = "Heritage Green 3", HomeTeam = "Victory FC", HomeScore = 3, AwayTeam = "Proto 4", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 6, 19, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 0, AwayTeam = "Sons of Italy Inter", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 10, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "West Hamilton United 89", HomeScore = 2, AwayTeam = "Hamilton Serbian United", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 10, 11, 0, 0), Field = "Mohawk 5", HomeTeam = "Proto 3", HomeScore = 2, AwayTeam = "Victory FC", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 10, 11, 0, 0), Field = "Heritage Green 2", HomeTeam = "Azzurri ST", HomeScore = 3, AwayTeam = "Sons of Italy Inter", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 10, 11, 0, 0), Field = "Heritage Green 3", HomeTeam = "Proto 4", HomeScore = 0, AwayTeam = "United FC", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 17, 9, 0, 0), Field = "Sackville", HomeTeam = "United FC", HomeScore = 0, AwayTeam = "Victory FC", AwayScore = 4, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 17, 11, 0, 0), Field = "Sackville", HomeTeam = "Azzurri ST", HomeScore = 0, AwayTeam = "Proto 3", AwayScore = 5, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 17, 11, 0, 0), Field = "Shady Acres 1", HomeTeam = "Hamilton Serbian United", HomeScore = 0, AwayTeam = "Proto 4", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 17, 9, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 2, AwayTeam = "West Hamilton United 89", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 24, 9, 0, 0), Field = "Heritage Green 3", HomeTeam = "Proto 3", HomeScore = 0, AwayTeam = "United FC", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 24, 9, 0, 0), Field = "Ancaster 3-A", HomeTeam = "Victory FC", HomeScore = 6, AwayTeam = "Hamilton Serbian United", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 24, 11, 0, 0), Field = "Heritage Green 5", HomeTeam = "West Hamilton United 89", HomeScore = 3, AwayTeam = "Azzurri ST", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 8, 24, 9, 0, 0), Field = "Proto Field", HomeTeam = "Proto 4", HomeScore = 1, AwayTeam = "Sons of Italy Inter", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 7, 9, 0, 0), Field = "Heritage Green 5", HomeTeam = "Azzurri ST", HomeScore = 1, AwayTeam = "Proto 4", AwayScore = 3, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 7, 11, 0, 0), Field = "Ancaster 3-A", HomeTeam = "West Hamilton United 89", HomeScore = 1, AwayTeam = "Proto 3", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 7, 9, 0, 0), Field = "Hamilton Italian Centre", HomeTeam = "Sons of Italy Inter", HomeScore = 3, AwayTeam = "Victory FC", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 7, 9, 0, 0), Field = "Mohawk 6", HomeTeam = "United FC", HomeScore = 2, AwayTeam = "Hamilton Serbian United", AwayScore = 0, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 14, 9, 0, 0), Field = "Proto Field", HomeTeam = "Proto 3", HomeScore = 1, AwayTeam = "Hamilton Serbian United", AwayScore = 1, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 14, 11, 0, 0), Field = "Proto Field", HomeTeam = "Proto 4", HomeScore = 2, AwayTeam = "West Hamilton United 89", AwayScore = 2, Competition = "regular" },
                new() { Date = new DateTime(2025, 9, 14, 11, 0, 0), Field = "Heritage Green 5", HomeTeam = "Victory FC", HomeScore = 8, AwayTeam = "Azzurri ST", AwayScore = 1, Competition = "regular" },

                // Spence Cup Matches (existing data)
                new() { Date = new DateTime(2025, 5, 11, 11, 0, 0), Field = "Brebeuf Turf # 1", HomeTeam = "Iam Emeralds ST", HomeScore = 1, AwayTeam = "Victory FC", AwayScore = 9, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 11, 13, 0, 0), Field = "Cardinal Newman HS (turf)", HomeTeam = "Glasgow United FC", HomeScore = 1, AwayTeam = "Sons of Italy Inter", AwayScore = 2, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 11, 9, 0, 0), Field = "Cardinal Newman HS (turf)", HomeTeam = "United FC", HomeScore = 4, AwayTeam = "Proto 3", AwayScore = 3, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 11, 11, 0, 0), Field = "Cardinal Newman HS (turf)", HomeTeam = "Proto 4", HomeScore = 0, AwayTeam = "Bell City FC", AwayScore = 3, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 11, 9, 0, 0), Field = "Brebeuf Turf # 1", HomeTeam = "Hamilton Croatia Hrvat", HomeScore = 0, AwayTeam = "Hamilton Serbian United", AwayScore = 1, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 28, 21, 0, 0), Field = "Bishop Ryan HS (turf)", HomeTeam = "Stoney Creek United", HomeScore = 0, AwayTeam = "West Hamilton United 89", AwayScore = 4, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 28, 21, 0, 0), Field = "Mohawk 2", HomeTeam = "Sons of Italy Inter", HomeScore = 2, AwayTeam = "Hamilton Serbian United", AwayScore = 1, Competition = "spence" },
                new() { Date = new DateTime(2025, 5, 28, 19, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 2, AwayTeam = "Bell City FC", AwayScore = 1, Competition = "spence" },
                new() { Date = new DateTime(2025, 6, 11, 21, 0, 0), Field = "Mohawk 2", HomeTeam = "Unipol FC", HomeScore = 1, AwayTeam = "Hamilton Juventus FC", AwayScore = 4, Competition = "spence" },
                new() { Date = new DateTime(2025, 6, 11, 19, 0, 0), Field = "Mohawk 2", HomeTeam = "Victory FC", HomeScore = 9, AwayTeam = "West Hamilton United 89", AwayScore = 2, Competition = "spence" },
                new() { Date = new DateTime(2025, 6, 25, 19, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 4, AwayTeam = "Sons of Italy Inter", AwayScore = 1, Competition = "spence" },
                new() { Date = new DateTime(2025, 6, 25, 21, 0, 0), Field = "Mohawk 2", HomeTeam = "Victory FC", HomeScore = 4, AwayTeam = "Hamilton Juventus FC", AwayScore = 0, Competition = "spence" },
                new() { Date = new DateTime(2025, 9, 3, 19, 0, 0), Field = "Mohawk 2", HomeTeam = "United FC", HomeScore = 2, AwayTeam = "Victory FC", AwayScore = 3, Competition = "spence" },

                // Playoff Matches
                new() { Date = new DateTime(2025, 9, 21, 9, 0, 0), Field = "Heritage Green #2", HomeTeam = "Victory FC", AwayTeam = "Azzurri", Competition = "playoff", Round = "quarterfinal", GameNumber = 1 },
                new() { Date = new DateTime(2025, 9, 21, 11, 0, 0), Field = "Heritage Green #2", HomeTeam = "Proto 3", AwayTeam = "United FC", Competition = "playoff", Round = "quarterfinal", GameNumber = 2 },
                new() { Date = new DateTime(2025, 9, 21, 9, 0, 0), Field = "Heritage Green #5", HomeTeam = "West Hamilton UTD", AwayTeam = "Proto 4", Competition = "playoff", Round = "quarterfinal", GameNumber = 3 },
                new() { Date = new DateTime(2025, 9, 21, 11, 0, 0), Field = "Heritage Green #5", HomeTeam = "Hamilton Serbian", AwayTeam = "SOI Inter", Competition = "playoff", Round = "quarterfinal", GameNumber = 4 },
                new() { Date = new DateTime(2025, 9, 28, 9, 0, 0), Field = "Heritage Green #5", HomeTeam = "TBD", AwayTeam = "TBD", Competition = "playoff", Round = "semifinal", GameNumber = 5 },
                new() { Date = new DateTime(2025, 9, 28, 11, 0, 0), Field = "Heritage Green #5", HomeTeam = "TBD", AwayTeam = "TBD", Competition = "playoff", Round = "semifinal", GameNumber = 6 },
                new() { Date = new DateTime(2025, 10, 5, 13, 0, 0), Field = "Heritage Green #4", HomeTeam = "TBD", AwayTeam = "TBD", Competition = "playoff", Round = "final", GameNumber = 7 }
            };

            return matches;
        }

        private static List<Scorer> GetInitialScorersData()
        {
            return new List<Scorer>
            {
                // Regular Season Top Scorers - Division C
                new() { PlayerName = "Tait Zachary", TeamName = "VICTORY FC", Goals = 15, Competition = "regular" },
                new() { PlayerName = "Pietrantuono Gaetano", TeamName = "PROTO 3", Goals = 12, Competition = "regular" },
                new() { PlayerName = "Beedham Tyler", TeamName = "VICTORY FC", Goals = 11, Competition = "regular" },
                new() { PlayerName = "O'Loughlin Conor", TeamName = "WEST HAMILTON UNITED 89", Goals = 10, Competition = "regular" },
                new() { PlayerName = "Palombi Christopher", TeamName = "VICTORY FC", Goals = 10, Competition = "regular" },
                new() { PlayerName = "Androich Joso", TeamName = "UNITED FC", Goals = 7, Competition = "regular" },
                new() { PlayerName = "Mcgrath Chris", TeamName = "WEST HAMILTON UNITED 89", Goals = 7, Competition = "regular" },
                new() { PlayerName = "Ruiu Roger", TeamName = "PROTO 4", Goals = 6, Competition = "regular" },
                new() { PlayerName = "Carvalho Nicholas", TeamName = "VICTORY FC", Goals = 6, Competition = "regular" },
                new() { PlayerName = "Cioca Paul", TeamName = "SONS OF ITALY INTER", Goals = 6, Competition = "regular" },
                new() { PlayerName = "Falletta Gerry", TeamName = "PROTO 3", Goals = 6, Competition = "regular" },
                new() { PlayerName = "Mceachnie Noel", TeamName = "SONS OF ITALY INTER", Goals = 5, Competition = "regular" },
                new() { PlayerName = "Chiaravalle Mike", TeamName = "PROTO 3", Goals = 5, Competition = "regular" },
                new() { PlayerName = "Ismail Said", TeamName = "WEST HAMILTON UNITED 89", Goals = 4, Competition = "regular" },
                new() { PlayerName = "Stratford Shaun", TeamName = "PROTO 3", Goals = 4, Competition = "regular" },
                new() { PlayerName = "Oddi Mark", TeamName = "SONS OF ITALY INTER", Goals = 4, Competition = "regular" },
                new() { PlayerName = "Hrastov Nenad", TeamName = "HAMILTON SERBIAN UNITED", Goals = 4, Competition = "regular" },
                new() { PlayerName = "Njegovan Dusan", TeamName = "HAMILTON SERBIAN UNITED", Goals = 4, Competition = "regular" },
                new() { PlayerName = "Lewis Trevor", TeamName = "VICTORY FC", Goals = 3, Competition = "regular" },
                new() { PlayerName = "Falletta David", TeamName = "AZZURRI ST", Goals = 3, Competition = "regular" },
                new() { PlayerName = "Pereira Rick", TeamName = "WEST HAMILTON UNITED 89", Goals = 3, Competition = "regular" },
                new() { PlayerName = "Macaluso Anthony", TeamName = "AZZURRI ST", Goals = 3, Competition = "regular" },
                new() { PlayerName = "CREPAR MARKO", TeamName = "UNITED FC", Goals = 3, Competition = "regular" },
                new() { PlayerName = "Tempral Jerome", TeamName = "PROTO 3", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Sardo Alex", TeamName = "SONS OF ITALY INTER", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Portillo Miguel", TeamName = "UNITED FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Locke David", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Ulysse Brendon", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Varela Yuri", TeamName = "SONS OF ITALY INTER", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Duran Marcin", TeamName = "UNITED FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Stefanovic Marko", TeamName = "HAMILTON SERBIAN UNITED", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Silvestri Lou", TeamName = "PROTO 4", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Mbuagbaw Lawrence", TeamName = "WEST HAMILTON UNITED 89", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Rominger Timothy", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Wirth Brent", TeamName = "UNITED FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Lara Erick", TeamName = "UNITED FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Kanlic Milan", TeamName = "HAMILTON SERBIAN UNITED", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Pace Eriberto", TeamName = "AZZURRI ST", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Gesse Ryan", TeamName = "PROTO 3", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Molinaro Albert", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "DiPaolo Christopher", TeamName = "PROTO 3", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Imgrund Mark", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Vrakela Jovan", TeamName = "HAMILTON SERBIAN UNITED", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Masirevic Sasha", TeamName = "HAMILTON SERBIAN UNITED", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Wright Sean", TeamName = "VICTORY FC", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Amorim Joe", TeamName = "PROTO 4", Goals = 2, Competition = "regular" },
                new() { PlayerName = "Gabinet Michael", TeamName = "UNITED FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Edwards Dan", TeamName = "WEST HAMILTON UNITED 89", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Bjelic Miodrag", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Genovese Aldo", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Vorkapic Nikola", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Caiazzo John", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Timperio Aldo", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Wilmot David", TeamName = "VICTORY FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Harrison Rob", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Duvnjak Jovo", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Giannini Brian", TeamName = "PROTO 4", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Ferro David", TeamName = "PROTO 4", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Stouffer Keith", TeamName = "VICTORY FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Milosevic Viktor", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Jashari Genc", TeamName = "UNITED FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Marcos Javier", TeamName = "VICTORY FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Toffolon Mark", TeamName = "PROTO 4", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Jack Darren", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Cavic Aleks", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Biggar George", TeamName = "VICTORY FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Giordano Giuseppe", TeamName = "PROTO 3", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Baxter Travis", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Labella Demetrio", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Carbone Daniel", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Riquelme Marco", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Falconio Anthony", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Dias Derek", TeamName = "PROTO 4", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Angemi Phil", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Fitzpatrick David", TeamName = "PROTO 4", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Cataldi JP", TeamName = "PROTO 3", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Schmutz Alan", TeamName = "WEST HAMILTON UNITED 89", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Zombeck Jonathan", TeamName = "VICTORY FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Zlataric Vladimir", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Cesareo Mario", TeamName = "AZZURRI ST", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Iacurti Bruno", TeamName = "PROTO 3", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Cotiga Flo", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Bratu Sorin", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "regular" },
                new() { PlayerName = "DANIELI OLIVER", TeamName = "UNITED FC", Goals = 1, Competition = "regular" },
                new() { PlayerName = "Telepakis Jimmy", TeamName = "PROTO 3", Goals = 1, Competition = "regular" },

                // M.Spence Cup - B
                new() { PlayerName = "Tait Zachary", TeamName = "VICTORY FC", Goals = 10, Competition = "spence" },
                new() { PlayerName = "Lewis Trevor", TeamName = "VICTORY FC", Goals = 4, Competition = "spence" },
                new() { PlayerName = "CREPAR MARKO", TeamName = "UNITED FC", Goals = 4, Competition = "spence" },
                new() { PlayerName = "Carvalho Nicholas", TeamName = "VICTORY FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Telepakis Jimmy", TeamName = "PROTO 3", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Lobo Christopher", TeamName = "UNITED FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Cychner Jakub", TeamName = "WEST HAMILTON UNITED 89", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Lara Erick", TeamName = "UNITED FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Pereira Rick", TeamName = "WEST HAMILTON UNITED 89", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Imgrund Mark", TeamName = "VICTORY FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Barnes Romaine", TeamName = "HAMILTON JUVENTUS FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Tinto Anthony", TeamName = "BELL CITY FC", Goals = 2, Competition = "spence" },
                new() { PlayerName = "Haye Rohan", TeamName = "HAMILTON JUVENTUS FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Zlataric Vladimir", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Bowers Andy", TeamName = "IAM EMERALDS ST", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Beedham Tyler", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Njegovan Dusan", TeamName = "HAMILTON SERBIAN UNITED", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Jack Darren", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Laracy Michael", TeamName = "BELL CITY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Kuri Guillermo", TeamName = "UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "DANIELI OLIVER", TeamName = "UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Desantis Gabriele", TeamName = "HAMILTON JUVENTUS FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Wilmot David", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Messoue Alain", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Wirth Brent", TeamName = "UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Locke David", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Rossini Renato", TeamName = "PROTO 3", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Labella Demetrio", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Sardo Kevin", TeamName = "WEST HAMILTON UNITED 89", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Mclean Gordon", TeamName = "GLASGOW UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Mathews Craig", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Calder Casey", TeamName = "BELL CITY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Ismail Said", TeamName = "WEST HAMILTON UNITED 89", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Bialy Waldemar", TeamName = "UNIPOL FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Androich Joso", TeamName = "UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Stathakos Nickos", TeamName = "UNITED FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Wright Sean", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Stouffer Keith", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Mceachnie Noel", TeamName = "SONS OF ITALY INTER", Goals = 1, Competition = "spence" },
                new() { PlayerName = "Cicoria Frank", TeamName = "VICTORY FC", Goals = 1, Competition = "spence" }
            };
        }
    }
}